#!/bin/bash
# Expected environment variables
# * role (first part of the hostname)
# * instance (second part of the hostname)
# * gitcmdb_repo (puppet repo to download)
# * gitcmdb_branch ( puppet repo branch)
# * gitcmdb_path (folder where to download the repo)

# check if puppet is installed

# check if repo is downloaded in gitcmdb_path, if not install it

# check if repo is in expected brach, if not change

# check if repo is updated

# run puppet if repo installed or updated
