#!/bin/bash
# Expected environment variables
# * role (first part of the hostname)
# * instance (second part of the hostname)
# * gitcmdb_repo (puppet repo to download)
# * gitcmdb_branch ( puppet repo branch)
# * gitcmdb_path (folder where to download the repo)
echo Running puppet installer

# check if puppet is installed
if [ ! -e /usr/bin/puppet ]; then
  if [ -e /etc/redhat_release ]; then
    sudo /bin/yum -y install puppet
  elif [ -e /etc/debian_version ]; then
    sudo /usr/bin/apt-get -y install puppet
  else
     echo "Unsuported distribution"
     return 1
  fi
fi

#check if r10k is installed
if [ ! -e /usr/local/bin/r10k ]; then
  sudo gem install r10k
fi

# check /etc/puppet link
if [ ! "$(readlink /etc/puppet)" = "$gitcmdb_path/gitdmdb_$gitcmdb_installer" ]; then
  sudo mv /etc/puppet /etc/puppet.`date +%s`
  sudo ln -sf $gitcmdb_path/gitdmdb_$gitcmdb_installer
fi

# install Puppetfile modules
sudo /usr/local/bin/r10k puppetfile install --puppetfile /etc/puppet/Puppetfile --moduledir /etc/puppet/modules

# run puppet
sudo /usr/bin/puppet apply /etc/puppet/manifests/site.pp
