#!/bin/bash
# Expected environment variables
# * role (first part of the hostname)
# * instance (second part of the hostname)
# * gitcmdb_repo (puppet repo to download)
# * gitcmdb_branch ( puppet repo branch)
# * gitcmdb_path (folder where to download the repo)
echo Running $0

# check if puppet is installed

# run puppet if repo installed or updated
